### ISSUE TITLE
Hue app crashed overnight

### ISSUE THREAD

**Issue by daneedk** [athombv/nl.philips.hue#37]
Homey 1.0.1
Hue 2.0.2

This morning it was impossible to switch any hue lights, I found out the hue app had crashed.
Error on warning icon:

Stack trace:

false

Exit code: null

Crashlog: B33B4B33D5

Disabling and enabling the app resulted in a rather long 'app loading' state, followed by the warning icon again and the same error. Any subsequent attempt at restarting did not get the app into loading state but straight to the error again.

A reboot resulted in a RROD.

After a PTP (™ @freemann) the app started without a problem.

If you need more info, please let me know.

Thanks.

**Comment by sossienl** [comment]
Same here

<img width="534" alt="screen shot 2016-11-20 at 14 28 15" src="https://cloud.githubusercontent.com/assets/609650/20463157/dd6a7e38-af2d-11e6-86c7-e4cf6f11d25a.png">

**Comment by Fire69** [comment]
Same here.
Working again after disable/enable of app.

**Comment by Tweaqer** [comment]
+1 for this error/crash

**Comment by sossienl** [comment]
It crashes every day. Please fix this asap.

**Comment by sossienl** [comment]
BTW after a crash, only a reboot helps. But every reboot ends in a red circle where you need to remove the power plug from the device.

**Comment by WeeJeWel** [comment]
Should be fixed in 2.1.0, the current commited version. Could you guys try it and see if it works better?

**Comment by daneedk** [comment]
Tried running 2.1.0:
<img width="647" alt="schermafbeelding 2016-11-21 om 22 14 22" src="https://cloud.githubusercontent.com/assets/16610696/20500941/f3307280-b037-11e6-91f2-8fa256aa63fe.png">

**Comment by sossienl** [comment]
Well I have 2.1 on my Homey (AppStore), but still crashes......

**Comment by WeeJeWel** [comment]
Can you send a Homey crashlog?

**Comment by sossienl** [comment]
24F86FB883

**Comment by WeeJeWel** [comment]
Thanks. This issue is fixed in the next version of Homey (v1.0.2)

**Comment by WeeJeWel** [comment]
(And by the way, the sunrise app is using 90% CPU most of the time on your Homey)

**Comment by sossienl** [comment]
Wow that's not good. I'll report it.

**Comment by Anamatronic** [comment]
What can i do to fix this?

Stack trace:

false

Exit code: null

Philips Hue v2.1.0
Homey Firmware Versie: 1.0.1

**Comment by WeeJeWel** [comment]
Wait for Homey v1.0.2 :)

**Comment by Anamatronic** [comment]
That takes a week?

**Comment by bvdbos** [comment]
scheduled for monday if no strange bugs appear 👍 
https://forum.athom.com/discussion/comment/38036/#Comment_38036

**Comment by bvdbos** [comment]
@daneedk This works now I presume?

**Comment by daneedk** [comment]
Yes, was fixed by 1.0.2.
