### ISSUE TITLE
Lightify bulbs switch to purple first when turned on

### ISSUE THREAD

**Issue by swttt** [athombv/nl.philips.hue#52]
My lightify bulbs that are connected trough the hue bridge switch to purple first before switching to its regular color.

Noticed that turning it on and off allot of times with the onoff capability it returns an error as well. Didn't save the error, but has something to do with "Hue couldn't set scene, so device turned off". I need to turn the lamp on with the hue app before it starts working again. (sometimes it does pick up the next ON command, so don't allways need the hue app. But does refuses to switch once.)

**Comment by VincentWRX** [comment]
I got the almost the same issue. When is switch on the lights with pulse switch or with a flow it goes purple.  But for me it doesnt go back to the latest light setting after some seconds. It stays purple.

**Comment by bvdbos** [comment]
This is fixed now?

**Comment by VincentWRX** [comment]
I will test later on. For now i'm not using the turn on function but i use the change to Scene function.

**Comment by bvdbos** [comment]
@VincentWRX Did you test this. Thought I read somewhere this was fixed?

**Comment by CyberSponk** [comment]
It's not fixed. Bulb turned red switching it on. Using scenes for switching on > No red. Not the best but works at the moment.

**Comment by swttt** [comment]
Weird, they turn purple-ish here now and stopped being red :)

**Comment by VincentWRX** [comment]
Same here they start purple now when i turn Them on

**Comment by WeeJeWel** [comment]
Please try again with version `3.0.0` (can be found in the `feature/sdk2` branch)

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by WeeJeWel** [comment]
Closed due to inactivity
